### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by khaosdoctor** [mediaupstream/SublimeText-Crypto#14]
Everytime I hit encrypt I get the message on console:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 11: ordinal not in range(128)

And nothing happens

**Comment by mediaupstream** [comment]
hi @khaosdoctor thanks for bringing this up. I will look into this when I get some time, until then all I can say is you might try encoding your data as utf-8 before you run Encrypt on the data. I think this is an issue with non utf-8 strings in Python...
