### ISSUE TITLE
Error: Wrong password?

### ISSUE THREAD

**Issue by daklang** [mediaupstream/SublimeText-Crypto#16]
Doesn't seem to work if there is no password. Just errors out.

**Comment by mediaupstream** [comment]
Are you using sublimetext 2 or 3, and what build number are you using? I tested encrypting/decrypting without password and it worked for me on sublimetext 3 build 3114.

**Comment by DOSputin** [comment]
On Arch Linux / Subl 3.2.1 build 3207  Same issue.  
Path to openssl is standard `/usr/bin/openssl` 

Any idea what could be the issue?  
Looked for logs, but didn't find anything.
