### ISSUE TITLE
Can't Paste password

### ISSUE THREAD

**Issue by ralovely** [mediaupstream/SublimeText-Crypto#18]
Hi.

_Thanks for this package, it's very handy and became a major part of my workflow._

Since the change where the password is replaced by `*`, I'm unable to paste the password anymore.
When pasting, it only shows one `*` (where typing it in shows the correct number).
and it results with the `Error: Wrong password?`.

With strong passwords, it can be quite painful.
Is it just me and my setup ?
(MacOSX 10.12.3, ST 3126, latest crypto from package manger)

Personally, I would gladly give up obfuscation to gain back ability to copy/paste.
If it can't be fixed, maybe it can be disabled via a setting ?

Thank you.

**Comment by Kristinita** [comment]
+1.

I reproduce the problem in Sublime Text Build 3126, Windows 10 64-bit.

Thanks.

**Comment by mediaupstream** [comment]
@ralovely I will add in the ability to enable/disable the password obfuscation for now while I work on a fix for copy/paste. Sorry for this bug, I'll get right on it.

**Comment by mediaupstream** [comment]
@ralovely I have updated the plugin so that password obfuscation is off by default until I find a fix for the copy/paste. If you don't need copy/paste and want passwords to be obfuscated while typing them you can enable it in the Crypto user settings by setting:
```json
"obfuscate_password": true
```

**Comment by ralovely** [comment]
Awesome. Works like a charm.

Thanks for this, and thanks again for the package.
Cheers.
