### ISSUE TITLE
Install instructions need to be updated for Sublime 3.

### ISSUE THREAD

**Issue by rgiampietro** [mediaupstream/SublimeText-Crypto#21]
Basically this:
git clone git://github.com/mediaupstream/SublimeText-Crypto.git ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/Crypto

needs to be this:

git clone git://github.com/mediaupstream/SublimeText-Crypto.git ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/Crypto

Awesome package guys, love it!

**Comment by mediaupstream** [comment]
Thanks for the suggestion. I updated the readme.
